#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Création du répertoire d'installation de Theia
ynh_script_progression --message="Creating installation directory..."
mkdir -p "$install_dir"
chown -R $app:www-data "$install_dir"

# Installation des dépendances
ynh_script_progression --message="Installing dependencies..."
ynh_install_app_dependencies nodejs yarn

# Configuration du fichier package.json
ynh_script_progression --message="Configuring package.json..."
cat > $install_dir/package.json <<EOF
{
  "private": true,
  "dependencies": {
    "@theia/callhierarchy": "latest",
    "@theia/file-search": "latest",
    # ...
  },
  "devDependencies": {
    "@theia/cli": "latest"
  }
}
EOF

# Installation et construction de Theia
ynh_script_progression --message="Installing and building Theia IDE..."
pushd "$install_dir"
ynh_exec_as $app yarn install
ynh_exec_as $app yarn theia build
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to Theia IDE..." --weight=1

# Configuration de NGINX
ynh_add_nginx_config

# Configuration du service systemd
ynh_script_progression --message="Configuring systemd service..."
ynh_add_systemd_config

# Intégration du service dans YunoHost
yunohost service add $app --description="Theia IDE" --log="/var/log/$app/$app.log"

# Utilisation de logrotate pour gérer les fichiers journaux
ynh_use_logrotate

# Configuration de Fail2Ban
ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================

# Ajout d'une configuration (si nécessaire)
# ...

#=================================================
# GENERIC FINALIZATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting Theia IDE..." --weight=1

# Démarrage du service systemd
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
